- lib/sequel/extensions/migration.rb
Hi!
I have some issues with migrations with missing files. After migrating files 1 and 3, for example, the version number saved on database is 2, so if I try to upgrade the database migration 3 is run again.
This patch should resolve it.
Thank you!
Bruno.
> Store correct version with IntegerMigrator with allow_missing_migration_files

- lib/sequel/database/transactions.rb
- spec/core/database_spec.rb
> Add before_retry transaction option

- CHANGELOG
Thanks again for fixing this :)
> fix small typo

- lib/sequel/extensions/dataset_source_alias.rb
Spotted a small typo with reading the doc. Thank you for this awesome library!
> Fix typo in docs

- doc/virtual_rows.rdoc
> Note infix operators in virtual rows' rdocs

- www/pages/plugins.html.erb
I recently made an [extension](https://github.com/refile/refile-sequel) for [Refile](https://github.com/refile/refile) to integrate it with Sequel.
> Add refile-sequel to list of external extensions

- README.rdoc
Many thanks for Sequel. Kudos.
Sorry for the lame pull request.
> fix two typos in README.rdoc

- lib/sequel/adapters/odbc.rb
- spec/integration/prepared_statement_test.rb
- spec/integration/type_test.rb
This is to convert bit fields to booleans for the ODBC adapter with `db_type: 'mssql'`.
As discussed in https://groups.google.com/forum/#!topic/sequel-talk/7OOaCQqg3r8
> Convert bit fields to booleans

- lib/sequel/adapters/jdbc/cubrid.rb
- lib/sequel/adapters/jdbc/db2.rb
- lib/sequel/adapters/jdbc/derby.rb
- lib/sequel/adapters/jdbc/h2.rb
- lib/sequel/adapters/jdbc/hsqldb.rb
- lib/sequel/adapters/jdbc/mssql.rb
- lib/sequel/adapters/jdbc/mysql.rb
- lib/sequel/adapters/jdbc/oracle.rb
- lib/sequel/adapters/jdbc/sqlanywhere.rb
- lib/sequel/adapters/jdbc/sqlite.rb
> Change to getLong() to accomodate BigInt primary key

- lib/sequel/model/base.rb
- lib/sequel/model/dataset_module.rb
- lib/sequel/plugins/inverted_subsets.rb
- spec/extensions/inverted_subsets_spec.rb
Adding inverted_subsets plugin as discussed on IRC.
> Inverted subsets

- lib/sequel/dataset/actions.rb
(having the :value made it look like it should be a hash inside
the :return value, which isn't right)
> Clarify :return option, it was a little ambiguous.

- README.rdoc
You shouldn't have to hover over every item in the resources list you should be able to just read it.
> rewrite resources list in readme

- lib/sequel/database/misc.rb
- spec/core/database_spec.rb
see
https://github.com/rails/rails/commit/1c2f52175008ffd4c31338138f5b11bff677123b
> allow IP6 hosts in database URL

- lib/sequel/dataset/actions.rb
> Fix typo in Dataset#insert documentation

- lib/sequel/adapters/shared/sqlite.rb
- spec/adapters/sqlite_spec.rb
SQLite has supported alternate conflict resolution algorithms since version
2.3.0. This patch adds support for `insert_conflict` which allows users to
specify an alternate algorithm such as IGNORE or REPLACE. A `insert_ignore`
method is also added for compatibility with MySQL.
> Add Dataset#insert_conflict on SQLite

- lib/sequel/plugins/validation_helpers.rb
Fixed a small typo in validation_helper.rb.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jeremyevans/sequel/1125)
> Fix typo in validation_helper.rb

- doc/opening_databases.rdoc
This is a basically a followup to https://github.com/jeremyevans/sequel/issues/1139, trying to help other people avoid making the same mistake that I have been doing. :smile:
> Added notes about how to avoid memory leaks

- lib/sequel/connection_pool.rb
- lib/sequel/connection_pool/sharded_single.rb
- lib/sequel/connection_pool/sharded_threaded.rb
- lib/sequel/connection_pool/single.rb
- lib/sequel/connection_pool/threaded.rb
- lib/sequel/database/misc.rb
- spec/core/connection_pool_spec.rb
- spec/core/database_spec.rb
as per https://groups.google.com/d/topic/sequel-talk/cQL2EB1BVtw/discussion
> concurrent option for preconnect

- lib/sequel/extensions/pg_range.rb
- spec/extensions/pg_range_spec.rb
Original discussion: https://groups.google.com/forum/#!topic/sequel-talk/kCZD4nMAdpY
Based on the work in pg_array.
Allows custom range types to be defined on a particular database instead of globally.
Supports looking up the oid and subtype oid from the pg_range table.
Also corrected an error message where a converter and subtype_oid were both provided.
> Register custom range types per Database

- lib/sequel/database/misc.rb
- lib/sequel/database/transactions.rb
This is the transaction refactoring required to support #1197 as an extension.
The extension itself is at https://github.com/chanks/sequel-savepoint-hooks
> Transaction refactoring

- lib/sequel/adapters/shared/oracle.rb
Pieced together using modified functions/snippets from the mysql and postgres adapters.  Smart about which versions of Oracle are supported (10g or later.)
> Regular expression support for Oracle 10g+ via REGEXP_LIKE

- spec/core/mock_adapter_spec.rb
Fixed typo while reviewing the tests for Sequel.mock
> Change "nedding" => "needing"

- doc/validations.rdoc
Remove superfluous apostrophe.
> Fix typo in validations.rdoc

- doc/sql.rdoc
- lib/sequel/adapters/shared/postgres.rb
- lib/sequel/sql.rb
* Added an example of changing the order to descending
* Added RDoc documentation for all window function options
> Improve documentation for window functions

- lib/sequel/plugins/class_table_inheritance.rb
to be able to understand what columns exactly are duplicated
> little more informative deprecation

- lib/sequel/adapters/shared/postgres.rb
- spec/adapters/postgres_spec.rb
> :materialized option for Sequel::Postgres::DatabaseMethods#views

- lib/sequel/adapters/mysql2.rb
- spec/adapters/mysql_spec.rb
> Add ability to disable streaming on mysql2 adapter

- lib/sequel/adapters/shared/oracle.rb
* Add special hanling for limit N offset 0
Oracle query optimizer can not recognize ROWNUM < 10 when ROWNUM is
aliased in subquery.
Adding special check for offset being 0 eliminates subquery, allowing
database to detect COUNT STOPKEY operation
* Use new syntax for FETCH NEXT ROWS for Oracle starting with v12, unless locking is used
> Add support for Oracle 12 limit/offset syntax

- lib/sequel/plugins/class_table_inheritance.rb
- spec/extensions/class_table_inheritance_spec.rb
Our use case is that we have a convention that _every_ table has an `updated_at` (or similar) column to make incremental ETLs to a data warehouse simpler. This breaks Sequel's CTI requirement that all columns in the inheritance tree be unique (excluding primary keys, of course).
The approach taken here is to have a list of columns that are ignored on _all_ sub-classes of the super class (where the `:class_table_inheritance` plugin is initialized). These columns are ignored during the initialization of the CTI plugin but also when retrieving data from the DB.
> allow sub-class columns to be ignored when using CTI

- spec/extensions/pg_json_spec.rb
I was reading tests and came across to this  minor typo.
> Fix typo in spec description

- lib/sequel/extensions/connection_expiration.rb
- spec/extensions/connection_expiration_spec.rb
This PR adds a configurable random delay (per-connection) to the connection timeout.
most tests are missing, please let me know if you have any input on that.
> [WIP] Connection expiration random delay

- lib/sequel/extensions/pg_static_cache_updater.rb
- lib/sequel/plugins/static_cache.rb
- spec/extensions/static_cache_spec.rb
Now we can reload the cache easy!
> Make `Model.load_cache` method public in `StaticCache` plugin

- lib/sequel/adapters/oracle.rb
- spec/adapters/oracle_spec.rb
I can't execute oracle procedure with CLOB value
> Add clob to mapping for bind params oracle

- doc/postgresql.rdoc
Hello @jeremyevans, faced this issue today. Hope it can help others
> Upsert: Explain how to upsert using existing column value

- lib/sequel/adapters/postgres.rb
> Support connection string for postgres

- lib/sequel/plugins/class_table_inheritance.rb
- spec/extensions/class_table_inheritance_spec.rb
As discussed at https://groups.google.com/forum/#!topic/sequel-talk/bstkQ29OQPs
> CTI plugin now uses the existing schema cache when available

- lib/sequel/dataset/query.rb
A little improvement for the great library 😍
> Fix a typo in the error message

- lib/sequel/adapters/mysql2.rb
Discussion: https://groups.google.com/forum/#!topic/sequel-talk/cEZfyAgvLZo
> Fix `Mysql2::Database#server_version` method

- www/pages/plugins.html.erb
This is a plugin I wrote to support an easy syntax for creating model through associations.
> Adds sequel-through plugin

- lib/sequel/plugins/plural_association_methods.rb
- spec/extensions/plural_association_methods.rb
Helpers for mass adding.
Accept only Arrays for additional arguments and composite keys support.
> Add `plural_association_methods` plugin with `add_*s` and `remove_*s` methods

- www/pages/plugins.html.erb
https://github.com/AlexWayfer/sequel-enum_values
> Add `sequel-enum_values` plugin to page

- doc/postgresql.rdoc
- lib/sequel/extensions/pg_json.rb
Trivial documentation clean-ups.
> Documentation typos

- doc/testing.rdoc
This may help out some inexperienced users migrating to Sequel from ActiveRecord. Otherwise they may spend a fair amount of time trying to make it work (as I did). I hope it helps.
> Add: DB constant definition

- lib/sequel/database/transactions.rb
Refactor when callbacks are fetched and calls inside `remove_transactions`, in order to make implementing extensions easier.
> Refactor when callbacks are fetched and calls inside remove_transactions

- lib/sequel/extensions/migration.rb
- spec/extensions/migration_spec.rb
Thanks for all your work on this amazing gem Jeremy + other maintainers.
I put this little hack in to my own code, and thought it might be useful for someone else. I will not be offended if it is not thought to be worth merging!
> Include source location of change block when raising error for irreversible migration

- doc/advanced_associations.rdoc
- doc/association_basics.rdoc
- doc/code_order.rdoc
- doc/model_dataset_method_design.rdoc
> Spell check a few rdoc files.

- lib/sequel/extensions/schema_dumper.rb
Hi,
This PR addresses a limitation I hit: one of my columns' type was "decimal(7,2) unsigned", which was not recognized and therefore treated as a string.
Cheers!
> Support unsigned decimals

- lib/sequel/plugins/dirty.rb
I guess it was accidentally added in d592153
> Remove duplicated comment line

- .github/workflows/ci.yml
Similar to the cleanup done in https://github.com/jeremyevans/roda/pull/200
> Cleanup for the CI workflow

- .ci.gemfile
- .github/workflows/ci.yml
- Rakefile
Change .ci.gemfile to alter from git protocol to https protocol. Change .github/workflows/ci.yml to use last PostgreSQL's version and set a password. Change Rakefile to set a password during PostgreSQL's connection. Everything tested in https://github.com/kaiquekandykoga/sequel/pull/1.
Thank you very much.
> Postgres latest

- README.rdoc
One Typo word was found and have been updated
> Typographical Error

- lib/sequel/dataset/query.rb
IDK: looks like it should be "emulating"?
> fix minor typo (?): "emualting" vs "emulating"

- doc/querying.rdoc
I thought I'd add in a complex query based on: https://github.com/jeremyevans/sequel/discussions/1939
I have found that reading examples, especially complex ones with joins etc. is particularly helpful. 
Due care has been taken, but it is possible i've made a mistake in the sql output.
> Add complex sample

- lib/sequel/extensions/connection_validator.rb
Thank you so much for Sequel—we love it!
> Minor typo

- README.rdoc
> Fix documentation typo
