jeremyevans/sequel

doc/validations.rdoc

The need for Sequel.extension :blank when using the :allow_blank validation helper is documented in the code comments, but not in the guide. So I added it.

Document use of Sequel.extension :blank with :allow_blank

---

lib/sequel/adapters/mysql2.rb

When using mysql2 adapter, Sequel.connect :charset option does not work correctly.
Mysql2 does not use :charset, it use only :encoding.

Mysql2 does not use :charset, it use only :encoding.

---

lib/sequel/extensions/pg_enum.rb
spec/extensions/pg_enum_spec.rb

As discussed on IRC, this PR adds the ability for create_enum in the pg_enum extension to be used in a reversible transaction.
I haven't added the spec yet, if you can let me know how to load the migration extension safely in pg_enum_spec.rb I will happily do that as well (or feel free to finish the job) :)

Allow create_enum to be used in a reversible migration

---

lib/sequel/plugins/json_serializer.rb
spec/extensions/json_serializer_spec.rb

I'm really loving the extension/plugin architecture of Sequel, thank you for making it that way.
I'm making a Sinatra app that is structured as a gem. So all classes, including Sequel models, are namespaced inside the main namespace. Currently Sequel does the following:
```rb
module Namespace
class Album < Sequel::Model
end
end
Namespace::Album.new.to_json(root: true) #=> "{"namespace/album": {}}"
```
I think a natural default key would be simply `"album"`. This goes along with the rest of Sequel where the namespace doesn't affect the name (e.g. table name). I know I could write `root: "album"`, but it gets tedious when you always need to pass it both to instance's and dataset's `to_json`.
I think this shouldn't be a backwards-incompatible change, because:
1. I believe it's a very rare …

Demodulize default root name in json_serializer

---

lib/sequel/database/misc.rb

When I first got the error, I couldn't quite figure out how to fix the problem. I think this error mostly happens when an extension is required on the wrong level. This error happened to me because I did this:
```rb
DB.extension :pg_json, :pg_json_ops
```

Improve error message of failed database extension

---

.travis.gemfile
lib/sequel/plugins/csv_serializer.rb
spec/extensions/csv_serializer_spec.rb

A plugin for working with CSV in the spirit of `json_serializer` and `xml_serializer`. The API is broadly similar to the existing serialization plugins, but because CSV is not a nested format, no attempt was made to support associations. It will of course properly escape values, accept alternative record separators, and so on, as it uses the standard `csv` library (or, on ruby < 1.9, `fastercsv`).
Past interest in CSV support:
* https://github.com/jeremyevans/sequel/issues/577
* https://groups.google.com/forum/#!searchin/sequel-talk/csv/sequel-talk/qq5OiXkn8LM/GKnFtR2VS84J
* https://groups.google.com/forum/#!searchin/sequel-talk/csv/sequel-talk/pUcaBSRc1_A/yLg21y49DoMJ
* http://stackoverflow.com/questions/24763711/reading-a-csv-file-into-ruby-using-sequel-and-the-sqlite3-gems
`fastercsv` …

csv_serializer plugin

---

lib/sequel/plugins/single_table_inheritance.rb

The hybrid_table_inheritance plugin uses the single_table_inheritance plugin.  Just like the class_table_inheritance plugin, hybrid overrides the table_name method to return the lowest table in the inheritance hierarchy.  But, the key column used by single_table_inheritance is on the root table.   The current version of hybrid_table_inheritance changes the result of table_name to the root table then calls the single_table_inheritance inherited method (super) then changes it back as shown here https://github.com/QuinnHarris/sequel-table_inheritance/blob/v0.1.3/lib/sequel/plugins/hybrid_table_inheritance.rb#L265
This request eliminates the need for this kludge.  Note that the table_name method typically used by single_table_inheritance returns dataset.first_source_alias

Change single_table_inheritance to use the dataset for the key column table name

---

lib/sequel/plugins/class_table_inheritance.rb
lib/sequel/plugins/single_table_inheritance.rb
spec/extensions/single_table_inheritance_spec.rb

This is intended to clean up the single and class table inheritance plugins a little bit by using inherited instance variables.  This passes specs and I don't expect it will change behaviour.  This is an aesthetic change so I don't mind if its rejected.

Change single and class to use Plugins.inherited_instance_variables

---

lib/sequel/extensions/pagination.rb

Hi Jeremy,
I was thinking that it would be useful to list the methods that the pagination extension provides in the documentation. Just so that it's not necessary to open the source code.

List pagination methods in the documentation

---

lib/sequel/adapters/shared/postgres.rb
spec/adapters/postgres_spec.rb

This makes adding a named conversion proc work for an enum type column.

this small patch makes add_named_conversion_proc also work for enum types

---

www/pages/plugins.html.erb

I created a plugin that helps eager loading associations when exposing objects in a JSON API.

Add link to sequel-jsonapi_eager external plugin

---

lib/sequel/adapters/shared/postgres.rb

Just and indentation fix, because it currently looks like this:

Fix documentation of #full_text_search

---

lib/sequel/adapters/jdbc.rb
spec/adapters/postgres_spec.rb

Hello,
I think there is missing option in StoredProcedureMethods#execute_insert that leads to fail for insert-like procedures when using JDBC adapter. I faced with it on Oracle but add a test for PG (also failed).
Best regards,
Nikita

Add missing sproc option

---

lib/sequel/extensions/pg_inet_ops.rb
spec/adapters/postgres_spec.rb
spec/extensions/pg_inet_ops_spec.rb

As discussed on IRC.
This isn't finished, as mentioned there are some bizarre spec errors I can't work out, need your help :)
A few points to work out for your thoughts..
* I'm not sure if all the operators and functions I defined are worth having, some of them are just overrides of standard operators (greater_than etc)
* Casting seems to be an issue in the PostgreSQL tests; when using a real column the server works it out, but when passing two strings, they need to be cast to inet and I'm not sure how to achieve this.
* The PostgreSQL tests sometimes return an IPAddr, sometimes a string, I'm not sure if this is consistent? In particular shouldn't the netmask function just return a string perhaps?
Let me know if I can do any more on this, or alternatively feel free to polish it up for …

Adding pg_inet_ops extension

---

lib/sequel/plugins/class_table_inheritance.rb
spec/extensions/class_table_inheritance_spec.rb
spec/extensions/hybrid_table_inheritance_spec.rb

This PR is the minimal change to replace the class_table_inheritance plugin with the hybrid_table_inheritance at http://github.com/QuinnHarris/sequel-table_inheritance
This adds and additional hybrid_table_inheritance_spec.rb test with test specific to features added over the existing class_table_inheritance plugin.

Change class_table_inheritance to use hybrid_table_inheritance code

---

lib/sequel/plugins/dirty.rb
lib/sequel/plugins/serialization.rb
spec/extensions/serialization_spec.rb

This PR makes the dirty plugin a bit more aware of changes happening inside serialized columns.
Previously, changing a serialized column made an entry in `changed_columns`, but not in `column_changes` (and hence `initial_values` etc) which was a bit inconsistent.
Now, everything in the dirty plugin is aware of the change. However this does bring about a new caveat - changing a serialized column from its initial value, then back again, leaves an entry in the dirty plugin structures (which the dirty plugin is supposed to prevent in the first place).
I couldn't see how to fix this (reset_column didn't seem to work) but I still think the new behaviour is an improvement, so I just added a note to the docs about it.

Make the dirty plugin notice when a serialized column is changed.

---

lib/sequel/sql.rb
spec/core/expression_filters_spec.rb

As discussed on the mailing list, this pull request adds the `=~` and `!~` methods to ComplexExpressions, so now the following query works.
```rb
DB[:movies].where{date.extract(:year) =~ 2015}
```

Add the =~ and !~ operators to ComplexExpression

---

lib/sequel/adapters/ibmdb.rb
lib/sequel/adapters/shared/db2.rb
spec/adapters/db2_spec.rb

As discussed in https://groups.google.com/forum/#!topic/sequel-talk/OwaKtriHeTk
1. Moves code to REORG during `alter_table` and `table_exists?` to DB2 shared adapter.
2. Overrides `apply_alter_table` to REORG after each ALTER TABLE operation.

Refactor DB2 REORG

---

lib/sequel/dataset/actions.rb
lib/sequel/exceptions.rb
lib/sequel/model/base.rb
spec/core/dataset_spec.rb

This way error handlers can inspect the exception to get the table name or even the model that originated it (if any).

Save a reference to the dataset with Sequel::NoMatchingRow

---

lib/sequel/extensions/pg_range.rb

It wasn't parsing properly: http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Postgres/PGRange.html#method-c-register

Fix indentation in rdoc for self.register

---

lib/sequel/plugins/csv_serializer.rb

This change will call the model method instead of returning raw value from the
database. It will make the CSV serializer consistent in behavior with JSON
serializer. Also, the InstanceMethod also calls the model methods rather than
returning a value.
```ruby
class Device < Sequel::Model
def management_ip
IPAddr.new(self[:management_ip], Socket::AF_INET)
end
end
```
```ruby
[16] pry(main)> Device.select(:management_ip).limit(1).to_csv
I, [2015-10-06T18:17:55.731001 #12379]  INFO -- : (0.000443s) SELECT `management_ip` FROM `device` LIMIT 1
I, [2015-10-06T18:17:55.732052 #12379]  INFO -- : (0.000564s) SELECT `management_ip` FROM `device` LIMIT 1
=> "168125324\n"
```
```ruby
[3] pry(main)> Device.select(:management_ip).limit(1).to_csv
I, [2015-10-06T18:18:52.490121 #14588]  INFO -- : …
```

call Model methods when serializing dataset

---

doc/validations.rdoc

This AR guide seems to have been split into two (Callbacks and Validations) since the link was made.

Fix broken link in validations.rdoc

---

doc/transactions.rdoc
lib/sequel/adapters/postgres.rb

Reason for change:
* The documentation wasn't clear about the default transaction when using Postgres cursors and I found myself stuck.
* The nice `use_cursor` method takes an option of `hold: true` which prevents rolling back all changes if a block fails, for example iterating over 10k records.
What the change was:
* Clarify that `use_cursor` uses a transaction by default and how to disable it.
* Add cursors to the Transactions document as another method which uses them by default.
Relevant discussion on the mailing list: https://groups.google.com/forum/#!topic/sequel-talk/7IRBCE-Rwv0

Update docs to reflect transaction use in cursors

---

doc/advanced_associations.rdoc
lib/sequel/model/associations.rb
spec/integration/associations_test.rb
spec/model/eager_loading_spec.rb

As discussed on sequel-talk. A couple of notes:
- The eager-loading association logic is a bit messier, by virtue of needing to passing around limit and offset information between methods, rather than being able to simply pull it from the association reflection when it was necessary. For backwards compatibility I made sure to not change the arguments required by any methods.
- I've added the support for Dataset#eager, but not Dataset#eager_graph. I started on the work for #eager_graph, but it seemed like it was going to be a more complicated addition and I wasn't planning on actually using the feature with #eager_graph, so I figured it would be safer and simpler to add it for #eager only and just document that the feature only works there. If you think it's important to also support it …

Support :eager_limit and :eager_limit_strategy Dataset options.

---

lib/sequel/adapters/jdbc.rb

Comments on columns are metadata in the schema. We can include them in the schema metadata.
[DatabaseMetaData.html#getColumns](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String))

JDBC: #schema_parse_table to include remarks

---

doc/active_record.rdoc

This adds a tip for users wishing to replicate AR's `none`. The example is taken from from [this](http://stackoverflow.com/a/36087167/1048479) SO answer.
Points of interest:
1. I'm not super famliar with RDOC, please let me know if I've made gaff
2. I'm not sure if the example should encourage extending every dataset. It seems like the clearest and cleanest way to do so (and fitting with how AR handles things)

Add "none" section to active_record docs

---

lib/sequel/dataset/actions.rb
lib/sequel/model/base.rb
spec/core/dataset_spec.rb
spec/integration/dataset_test.rb

Using to_hash (or select_hash, or _groups) to build quick lookups from datasets and models is extremely handy, but I find myself writing constructs like this:
```ruby
lookup = Hash.new do |hash, key|
hash[key] = MyModel.new :key => key, :value => "unknown"
end.merge! MyModel.to_hash(:key)
```
or:
```ruby
lookup = Hash.new(["unknown"])
.merge! DB[:my_table].select_hash_groups(:key, :value)
```
This patch adds an optional `:hash` parameter to the various hash methods, into which entries are merged. This allows slightly more readable versions of the above:
```ruby
lookup = MyModel.to_hash :key, nil, :hash => Hash.new do |hash, key|
hash[key] = MyModel.new :key => key, :value => "unknown"
end
```
and:
```ruby
lookup = DB[:my_table].select_hash_groups(:key, :value, :hash => …
```

Add optional block parameter to dataset hash methods

---

lib/sequel/plugins/update_or_create.rb

This is an extremely minor change, happend to notice that there was a reference to `create_or_update` where it should have been `update_or_create` in the documentation for the UpdateOrCreate plugin.

Correct reference to create_or_update in UpdateOrCreate docs

---

CHANGELOG
doc/validations.rdoc
lib/sequel/plugins/validation_helpers.rb
spec/extensions/validation_helpers_spec.rb

This checks that an attribute compares favourably against a specified
value for a given operation, e.g.
class Example < Sequel::Model
def validate
super
validates_operator(:>, 3, :something)
end
end
Feature discussion:
https://groups.google.com/forum/#!topic/sequel-talk/EMrbjLFrJpA

Add validates_operator validator

---

lib/sequel/extensions/migration.rb

Running migrations in ruby 2.3.0 gives us the following:
> ›  git:(master) bundle exec sequel -m db postgres://127.0.0.1:5432/database
Assertion failed: (!STR_EMBED_P(shared)), function str_new_frozen, file string.c, line 1075.
zsh: abort      bundle exec sequel -m db postgres://127.0.0.1:5432/database
While it works properly locally.
The `version_numbers` method is called twice, and this error happens on `File.basename`.
Memoizing the method hides that error, as only the second call causes the issue.
I have a repro project so simple, I can paste it here:
```
diff --git a/Gemfile b/Gemfile
new file mode 100644
index 0000000..4f3759b
--- /dev/null
+++ b/Gemfile
@@ -0,0 +1,5 @@
+source 'http://rubygems.org'
+
+ruby '2.3.0'
+gem 'pg'
+gem 'sequel'
diff --git a/Gemfile.lock b/Gemfile.lock
new …
```

Memoize version_numbers

---

doc/validations.rdoc

Fix typo in validates_format docs (\a -> \A)

---

lib/sequel/adapters/ado.rb
lib/sequel/adapters/amalgalite.rb
lib/sequel/adapters/cubrid.rb
lib/sequel/adapters/do.rb
lib/sequel/adapters/ibmdb.rb
lib/sequel/adapters/jdbc.rb
lib/sequel/adapters/mock.rb
lib/sequel/adapters/mysql.rb
lib/sequel/adapters/mysql2.rb
lib/sequel/adapters/odbc.rb
lib/sequel/adapters/oracle.rb
lib/sequel/adapters/postgres.rb
lib/sequel/adapters/sqlanywhere.rb
lib/sequel/adapters/sqlite.rb
lib/sequel/adapters/swift.rb
lib/sequel/adapters/tinytds.rb
lib/sequel/dataset.rb
lib/sequel/dataset/actions.rb
lib/sequel/extensions/columns_introspection.rb
lib/sequel/extensions/duplicate_columns_handler.rb
spec/extensions/duplicate_columns_handler_spec.rb

Original discussion: https://github.com/jeremyevans/sequel/issues/954
Continuation: https://github.com/TSMMark/sequel/pull/2
The duplicate_columns_handler extension allows you to customize handling of duplicate column names in your queries on a per-database or per-dataset level.

Extension: Duplicate columns handler

---

CHANGELOG
lib/sequel/model/base.rb
spec/model/record_spec.rb

Previously lock! locked the row the model represented with whatever
Dataset#for_update resolved to for the underlying database. This
changes it to accept an optional style of lock that will be aquired
instead (working as Dataset#lock_style does):
e = Example.first
e.lock!
#=> SELECT * FROM examples WHERE id = 1 FOR UPDATE LIMIT 1
e = Example.first
e.lock!('FOR NO KEY UPDATE')
#=> SELECT * FROM examples WHERE id = 1 FOR NO KEY UPDATE LIMIT 1

Change Sequel::Model#lock! to accept a lock style

---

lib/sequel/adapters/jdbc.rb

When I had a bad connection string and it was unable to connect, the error exception's message was a frozen String, which led to me not being able to see it, since `#connect` seems like it wants to `<<` onto the `e2.message`. jruby-9.1.2.0
This PR tries to edge around that problem by replacing the full string instead of appending to it.
```
Sequel::DatabaseConnectionError: RuntimeError: can't modify frozen String
/home/foobar/.app-gems/jruby/2.3.0/gems/sequel-4.36.0/lib/sequel/adapters/jdbc.rb:227:in `connect'
/home/foobar/.app-gems/jruby/2.3.0/gems/sequel-4.36.0/lib/sequel/connection_pool.rb:110:in `make_new'
/home/foobar/.app-gems/jruby/2.3.0/gems/sequel-4.36.0/lib/sequel/connection_pool/threaded.rb:226:in `make_new'
/home/foobar/.app-gems/jruby/2.3.0/gems/sequel-4.36.0/lib/sequel/connec …
```

JDBC#connect: obey the frozen string literal rule

---

lib/sequel/extensions/migration.rb
spec/extensions/migration_spec.rb

If you are using postgresql and you want to have a reversible migration with an `add_constraint` and `:not_valid => true` like this:
```ruby
Sequel.migration do
change do
alter_table :my_table do
add_constraint({:name => :new_check, :not_valid => true}, 'col_a > 5')
end
end
end
```
You will get an error like this: `PG::UndefinedObject: ERROR:  constraint "{:name => :new_check, :not_valid => true}" of relation "my_table" does not exist`
This patch fixes this.

Make MigrationAlterTableReverser work with add_constraint with name in a hash

---

lib/sequel/extensions/pg_interval.rb
spec/extensions/pg_interval_spec.rb

See #1232. This fix is pretty simple and only handles literalization, to remain backwards compatible with earlier versions of ActiveSupport. I suppose it'd be nice to tweak the parsing to populate the week and hour parts, but it'd require checking the current version of ActiveSupport supports that, and felt like it wouldn't really be worth the trouble.

Support weeks and hours in pg_interval extension.

---

doc/schema_modification.rdoc
lib/sequel/adapters/shared/mysql.rb
spec/adapters/mysql_spec.rb

This PR allows columns to be added at a specific position within a table row by using `AFTER` and `FIRST` when using `alter_table(:some_table) { add_column ... }` MySQL schema generators.

Supports AFTER and FIRST MySQL column positioning options for migrations

---

lib/sequel/adapters/shared/postgres.rb
spec/adapters/postgres_spec.rb

I have a partial unique index, declared like `index [:a, :b], unique: true, where: {c: true}`. Postgres supports using it in an ON CONFLICT clause by specifying the index predicate as part of the target, e.g. `INSERT ... ON CONFLICT ("a", "b") WHERE ("c" IS TRUE) DO UPDATE ...`. Unfortunately, Sequel doesn't support that part of ON CONFLICT yet, so here's a small PR implementing it.
(Side note: I initially tried to work around this issue by passing a constraint name to `insert_conflict`'s constraint naming option, but unfortunately Postgres doesn't support filters on unique constraints, only unique indexes, and it won't accept being passed an index name rather than a constraint name. So it looks like the only way to support this use case in Sequel is via a patch like this.)
The only …

Support specifying the predicate of a partial unique index in Dataset#insert_conflict

---

lib/sequel/adapters/ado.rb

`ADODB.Connection#Execute` returns an *open* recordset for a row-returning query (and a closed recordset for a non-row-returning query).
Since it's an open recordset, it will remain in memory until it's either closed, or it's associated connection object is closed (which is never, thanks to connection pooling).
(If I understand correctly, ADO adapter's `execute` method is for row-returning queries only, and for non-row-returning queries, `execute_dui` is used instead. Please correct me if I'm wrong, in which case I may need to add a `rescue nil` after `r.close`)

Fix a memory leak in ADO adapter's execute method

---

lib/sequel/adapters/ado.rb
lib/sequel/adapters/ado/mssql.rb
lib/sequel/extensions/sql_comments.rb
spec/integration/dataset_test.rb

**My setup:**
```
C:\Users\Administrator\GitHub\sequel>cat spec\spec_config.rb
DB = Sequel.ado(
provider: "SQLNCLI10",
conn_string: "Provider=SQLNCLI10;Server=.\\SQLEXPRESS;Database=SEQUEL;Uid=sa;Pwd=sa1234;"
)
```
**Before this patch:**
```
Run options: --seed 25653
1) Failure: MSSSQL::Dataset#insert#test_0004_should allow large text and binary values [C:/Users/Administrator/GitHub/sequel/spec/adapters/mssql_spec.rb:374]:
2) Failure: Dataset#unbind#test_0002_should handle numerics and strings [C:/Users/Administrator/GitHub/sequel/spec/integration/prepared_statement_test.rb:434]:
3) Failure: Dataset#unbind#test_0003_should handle dates and times [C:/Users/Administrator/GitHub/sequel/spec/integration/prepared_statement_test.rb:439]:
4) Failure: RETURNING clauses in INSERT#test_0001_should …
```

Pass more MSSQL integration specs using ADO adapter

---

spec/adapters/mssql_spec.rb

I noticed that after running integration specs, there is always one table, `MY.FOO`, left over in the test database. The reason it is not getting cleaned up is because the cleanup code in the `after` block that deletes the `foo` table assumes that this table is in the default schema. But this table is not in the default schema because `DB.rename_table Sequel[:MY][:bar], :foo` means "rename `MY.BAR` to `MY.FOO`", **not** "rename `MY.BAR` to `dbo.FOO`". I.e. renaming does not work across schemas, and the cleanup code needs to take this into account.

MSSQL::Database#rename_table does not work across schemas

---

lib/sequel/plugins/json_serializer.rb
spec/extensions/json_serializer_spec.rb

add :name option to :include hash to specify the name of the association.
tested in 1.8.7, 1.9.3 and 2.3.1
compared using JSON.parse, because 1.8.7 reversed the keys in the hash ;)
added the example in the rdoc comments (but I guess the doc directories are git ignored...). I noticed that the examples don't quite show whats expected (they have json_class as a key) but I followed that style in case I missed something!

specify the name of an association in json_serialize plugin

---

lib/sequel/plugins/json_serializer.rb
spec/extensions/json_serializer_spec.rb

the alias expression for an association did not work when used standalone (or in an array), this fixes that - didn't spot it before!

fix Sequel alias expression when not used in hash context

---

lib/sequel/adapters/shared/sqlite.rb
spec/adapters/sqlite_spec.rb

here is the command i used
```
SEQUEL_SQLITE_URL=sqlite:/ ruby spec/adapters/sqlite_spec.rb && SEQUEL_INTEGRATION_URL=sqlite:/ ruby spec/integration/schema_test.rb
```
and this one also passes
```
SEQUEL_INTEGRATION_URL=sqlite:/ rake spec_sqlite
```

sqlite preserves autoincrement on duplicate

---

doc/migration.rdoc

Spent some time searching for the appropriate way to add extensions (pg_enum, pg_json) to standalone migrations using the `sequel` CLI. Thought I should add some quick docs while I was here. Open to any suggestions to improve/add/modify. Or, if this exists somewhere else, please let me know. Maybe my googling skill isn't so great.

Add note about adding extensions

---

lib/sequel/adapters/shared/sqlite.rb

Hello @jeremyevans 
I've found ROM's specs are failing on translating SQLite exceptions on JRuby. That's because jdbc-sqlite3 adapter [was updated](https://github.com/jruby/activerecord-jdbc-adapter/commit/754c63c7ef169cb0c919c2d443cb343f164d779b) recently. The release introduced extended exception codes added to Java adapter [in June](https://github.com/xerial/sqlite-jdbc/commit/7509994a073c1a16d98be93de5ca7cacdbfd700b). I used [the approach](https://github.com/jeremyevans/sequel/blob/f526db79aebc2231a5c74f5292f48b6af12eac1f/lib/sequel/adapters/oracle.rb#L144-L160) from Oracle's adapter to pick a proper exception class, then tested the changes with `jdbc-sqlite3` v3.8.11.2 (without ext. codes) and v3.15.1 (with codes), works fine on both, but let Travis verify it.

Use exception codes for SQLite on JRuby

---

lib/sequel/adapters/postgres.rb

Hello!  This pull request is in regards to #1297.
A few notes:
* Just using `gem` instead of `require` seems the most natural way to do this, but rescuing/warning became more involved when dealing with bundler's different exception classing.  Trying to default to being unobtrusive, and adding special casing for bundler doesn't feel appealing.
* If the environment doesn't have sequel_pg installed via gem, but it's still in the $LOAD_PATH, the behavior is "just as it was" beforehand.
* I omitted the check for the Windows bit... the sequel_pg docs claim there isn't recent Windows support anyway, so it feels like you're on your own in a Windows environment regardless.  Not sure what feelings are surrounding that.

Raise early if the installed version of sequel_pg is too old to behave reliably

---

lib/sequel/core.rb
spec/core/expression_filters_spec.rb

This fixes boolean pg_array conversion:
>> DB.schema(:foos).last
=> [**:barray**, {:oid=>1000, :db_type=>"boolean[]", :default=>nil, :allow_null=>true, :primary_key=>false, :type=>**:boolean_array**, :ruby_default=>nil}]
>> x = Foo.new
=> #<Foo @values={}>
>> x.barray = [ false, true, false ]
=> [false, true, false]
>> x.barray
=> [nil, true, nil]

fix: convert non-nil elements

---

.travis.yml

This PR changes the test matrix to test the latest stable JRuby.

Travis: test on jruby-9.1.7.0

---

.travis.yml

This PR adds a `before_install` step to install a Bundler, in order to see if  jruby-head can build.
**Update**: That did it. It now runs, see [Travis build configured on my fork](https://travis-ci.org/olleolleolle/sequel).
And, comes up with a test failure on jruby-head:
```
1) Failure:
Supported types#test_0010_should support generic time type [/home/travis/build/olleolleolle/sequel/spec/integration/type_test.rb:83]:
Expected: "'19:49:16.047188'"
Actual: "'19:49:16.047000'"
```

Travis: gem install bundler

---

doc/opening_databases.rdoc

I wrapped this up some week ago, for our own convenience: https://rubygems.org/gems/jdbc-jt400
(Feel free to rephrase as you see fit.)

Added note about the jdbc-jt400 gem

---

lib/sequel/model/base.rb

Ruby (with warning option) warns about it:
```
/Users/tagomoris/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.43.0/lib/sequel/model/base.rb:2045: warning: assigned but unused variable - m
```

remove additional/unused variable assignment

---

lib/sequel/extensions/schema_dumper.rb
spec/extensions/schema_dumper_spec.rb

Passing options from schema_dump method to schema method, so database
can differ from schemas
A database with multi schemas don't diff the schema that must be filtered.
As schema method already accept schema options, just passing from
method caller

Schema dump ignoring database schema

---

lib/sequel/extensions/migration.rb
spec/extensions/migration_spec.rb

Helps pinpointing issues in migrations. At least for me.
Many thanks for Sequel.

Indicate in error message which is the file with the empty migration

---

lib/sequel/adapters/jdbc/sqlserver.rb
spec/adapters/mssql_spec.rb

DateTimeOffset should be returned as a ruby Time instead of the raw jdbc type.

Add TypeConvertor jdbc/sqlserver DateTimeOffset

---

lib/sequel/adapters/jdbc/as400.rb

I just read this message when running a Sequel-based app and realized it could make sense to change this, to avoid people doing multiple versions of the adapter when the work has already been started there.

Added note about the sequel-jdbc-as400 gem

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.

Travis: update to latest JRuby, jruby-9.1.10.0

---

lib/sequel/adapters/jdbc/postgresql.rb

If bad params are provided to the copy_into command, copier object doesn't get instantiated. This causes an error (NoMethodError Exception: undefined method `cancelCopy' for nil:NilClass) at [line: 76](https://github.com/jeremyevans/sequel/blob/1c409a402257095cf2d0f936404f1fa25182f0fe/lib/sequel/adapters/jdbc/postgresql.rb#L76).
This masks the original error being raised.

Postgres JDBC adapter - code breaks inside rescue

---

lib/sequel/extensions/pg_array.rb
spec/extensions/pg_array_spec.rb

When parsing a PostgreSQL text array we want to have the same encoding
set for the members of the array as we had for the array literal, rather
than having them use Ruby's ASCII-8BIT encoding.
I encountered this issue when another gem, simpleidn, turned out to be picky about receiving ASCII-8BIT encoded input. That could be a bug in simpleidn, but I still think this should be fixed in Sequel.

Preserve encoding when parsing PostgreSQL arrays

---

lib/sequel/adapters/postgres.rb

Right now it is being swallowed:
```ruby
dsn = "postgres://u:p@host.com/db?sslmode=verify-full&sslrootcert=path-to-bundle.pem"
PG.connect(str).exec('select 1').to_a # works
Sequel.connect(dsn)['select 1'].to_a 
```

Forward `sslrootcert` option through to pg driver

---

lib/sequel/plugins/single_table_inheritance.rb
spec/extensions/single_table_inheritance_spec.rb

Now you can select the subclass based on the type value.
This is useful in APIs and other places where you don't
know which subclass to instantiate.

Separate out selecting class logic in sti plugin

---

lib/sequel/adapters/jdbc/postgresql.rb
spec/adapters/postgres_spec.rb

Up until now the length of the original input was passed on as length of the buffer. However a call to `to_java_bytes` might return several bytes for a single character depending on the encoding. In the end only part of the actual data would have been sent to the PostgreSQL server either leading to missing line endings and thus mixing several rows into one or finding invalid bytes for certain encodings.
It would be really great to also backport this to the v4 branch. If we can help in any way, just get back to us. Thanks.

Fix buffer length passed on to writeToCopy (JRuby)

---

lib/sequel/model/associations.rb

Fix this warning:
```
~/.gem/ruby/2.4.1/gems/sequel-5.0.0/lib/sequel/model/associations.rb:2546:
warning: assigned but unused variable - res
```
I also saw this one:
```
~/.gem/ruby/2.4.1/gems/sequel-5.0.0/lib/sequel/dataset/query.rb:84: warning:
statement not reached
```
not sure how to suppress it 🤔

Fix a warning: assigned but unused variable

---

lib/sequel/extensions/pg_inet.rb

Since we do not parse PostgreSQL's macaddr type in the pg_inet extension
there is no reason for us to look up the oid of macaddr when specifying
a conversion proc for macaddr[], and the avoid this lookup we have to
explicitly specify a noop conversion proc.

Skip unnecessary database lookup of macaddr's oid

---

lib/sequel/adapters/postgres.rb

There is a double "should should", so this fixes it.

Fix typo in RDocs

---

lib/sequel/adapters/oracle.rb

ORA-02396, which is an idle timeout, should be considered a connection error.
`ORA-02396: exceeded maximum idle time, please connect again`
Existing tests pass, but there are no tests that deal with oracle connection errors.

Add ORA-02396 as a connection error

---

lib/sequel/extensions/synchronize_sql.rb
spec/extensions/synchronize_sql_spec.rb

The MySQL adapter checks out a connection in order to do placeholder
escaping; this means that for queries with large numbers of placeholders
in them, a large amount of time can be spent checking out/checking in
connections while building up the SQL test.
This PR adds a dataset extension which wraps the _sql generation methods
with `db.synchronize`, so that only one connection is checked out for
the entire SQL generation process.
This should resolve jeremyevans/sequel#1319

Add PlaceholderCheckout dataset extension for MySQL

---

lib/sequel/extensions/null_dataset.rb
spec/extensions/null_dataset_spec.rb

I use Dataset#nullify a fair amount in an app (it winds up being very helpful for resolving GraphQL requests, where the pagination logic is often very removed from the filtering logic), and it'd be nice if it were be able to chain cached datasets off of it.

Cache calls to Dataset#nullify.

---

doc/cheat_sheet.rdoc
doc/querying.rdoc

There were too many notes in the `last` method documentation and it did not clearly convey `last` behavior to me in a strong concise manner. `last` missing in cheat sheet and removed `just` - superfluous.
I had trouble with word wrapping at 80 and keeping the numbered bullets in correct order.

Improve documentation for #last

---

lib/sequel/database/query.rb

Shadowing outer local variable v

---

doc/association_basics.rdoc

Noticed a tiny formatting error when reading through this doc today.

Fix code example indentation in Association Options section

---

lib/sequel/model/base.rb
spec/model/base_spec.rb

Because `.dataset` raises error if there is no dataset,
and there is no quiet way to check dataset existing, except `rescue`.
Useful for multiple-inherited abstract classes.
Reference: https://groups.google.com/d/msg/sequel-talk/OG5ti9JAJIE/G8ncUsT4BAAJ

Add `Sequel::Model.dataset?` method

---

lib/sequel/adapters/shared/mysql.rb
lib/sequel/database/features.rb
lib/sequel/database/schema_generator.rb
spec/adapters/mysql_spec.rb

Generated Columns feature is [`T175`](https://ronsavage.github.io/SQL/sql-2003-noncore-features.html) in the SQL-2003 standard.
Supported by [MariaDB 5.2.0+](https://mariadb.com/kb/en/library/generated-columns/) and [MySQL 5.7.6+](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-6.html).
The standard BNF grammar for a [`<generation clause>`](https://ronsavage.github.io/SQL/sql-2003-2.bnf.html#generation%20clause) is
`GENERATED ALWAYS AS (`[`<value expression>`](https://ronsavage.github.io/SQL/sql-2003-2.bnf.html#value%20expression)`)`.
This PR adds:
- `:generated_always_as` option to column definition to add a `GENERATED ALWAYS AS column expression` to column definition statements;
- `#supports_generated_columns?` method that specifies whether the database supports generated …

Generated columns support

---

lib/sequel/adapters/shared/postgres.rb
lib/sequel/sql.rb

It seems that `{SomeClass}` isn't the right way to link classes in RDoc, because it doesn't work (probably mixed it up with YARD). So I changed it to the full class name, and that works. In that case the link text will be the full constant name (`Sequel::SQL::Window`).

Fix Sequel::SQL::Window RDoc links

---

lib/sequel/plugins/list.rb
spec/extensions/list_spec.rb

This adds an option to the list plugin to allow overriding the default of 1 for the top of the list position.
I'm not sure whether whether this could do with more tests, I'd be happy to add them if you let me know.

Add :top as an option in the list plugin

---

lib/sequel/model/base.rb

This removes an extra indent that was probably unintentional.

Fix Rdoc indent

---

lib/sequel/model/associations.rb

Since it's not clear from reading the RDocs of `#association_join` what kind of arguments it receives (the same kinds as `#eager` and `#eager_graph`), I thought it would be good to add examples to RDocs.
While here, I also often missed examples in `#eager` and `#eager_graph` RDocs, so I added them as well. I know these examples are already present when you scroll to the top of that RDoc document, but many people might know that, and I think it's good to have a bit of redundancy in the documentation.

Add examples for #association_join, #eager and #eager_graph

---

lib/sequel/model/associations.rb

Addressing https://github.com/jeremyevans/sequel/pull/1545#issuecomment-421734619. I also added some short descriptions as I thought it would be useful, especially for clarifying the filter blocks. This also removes some superfluous `.all` calls in the `#association_join` examples.

Show association filtering for #association_join, #eager and eager_graph

---

lib/sequel/dataset/prepared_statements.rb
spec/core/dataset_spec.rb
spec/integration/prepared_statement_test.rb

This pull request adds `:single_value` as a supported type for prepared statements, allowing single-column queries for counts, averages, etc. to be prepared.

Support single_value type in prepared statements

---

lib/sequel/plugins/tree.rb
spec/extensions/tree_spec.rb

It is usefull when used with associations.
I.e. `foo.bars_dataset.roots`

Make roots and roots_dataset to dataset methods in tree plugin

---

lib/sequel/sql.rb

I've often forget the `Sequel.case` arguments, and when I would look at the docs it would take me some time to figure out which argument is for what. So I updated the documentation to explain each argument, and to go from simpler to more complex examples.
I also added the hash variant for the sub-expression example, as I find it much more intuitive than an array. It also makes it clearer that it's just an extension of the "simple column value" example.

Improve Sequel.case documentation

---

lib/sequel/sql.rb

There are some examples which assume that core extensions are loaded, so I updated those to use `Sequel[]`. I also replaced some `Sequel.lit` instances with `Sequel[]` for consistency with other examples.

Normalize some RDocs

---

lib/sequel/plugins/class_table_inheritance.rb
spec/extensions/class_table_inheritance_spec.rb

From discussion here: https://groups.google.com/forum/#!topic/sequel-talk/Awt--16UGLw
I used your suggestion of setting `@cti_alias` as the unqualified identifier rather than coercing into a string, I think that made more sense than my naive implementation.

Fix default class table inheritence alias when dataset is qualified

---

doc/validations.rdoc

This PR fixes a typo. Thanks for keeping so much documentation!

[doc] Fix typo overridding -> overriding

---

.travis.yml

TruffleRuby works on Travis finally. https://github.com/travis-ci/travis-build/pull/1604 It always installs the latest version of TruffleRuby.
Sequel specs don't pass now. One of the reasons why not passing `Object#clone(freeze)` is not supported yet but the fix is coming soon in the next release https://github.com/oracle/truffleruby/issues/1454
I believe running specs on TruffleRuby would help its developers

Run specs also on TruffleRuby on Travis CI

---

lib/sequel/plugins/auto_validations.rb
spec/extensions/auto_validations_spec.rb

It is useful e.g. for non-interactive updates where multiple instances swap values in unique columns in a transaction (using a deferred unique constraint).

Enable skipping of auto_validations on a per-model-instance basis.

---

lib/sequel/extensions/pg_enum.rb
spec/adapters/postgres_spec.rb
spec/extensions/pg_enum_spec.rb

This ability was added into PostgreSQL 10: https://commitfest.postgresql.org/10/588/

Add `#rename_enum_value` method for `pg_enum` extension

---

lib/sequel/extensions/schema_dumper.rb
spec/extensions/schema_dumper_spec.rb

I was playing around with the "schema_dumper" earlier today and I noticed that some of my "float unsigned" column (coming from MySQL) were wrongly converted into strings because it didn't match the regexp for the Float type so fixed it.

Added support for 'float unsigned' in the schema_dumper extension.

---

doc/dataset_filtering.rdoc

I was looking for documentation on how to combine AND and OR filtering in the same dataset, but couldn't find anything on 
* http://sequel.jeremyevans.net/rdoc/files/doc/querying_rdoc.html
* http://sequel.jeremyevans.net/rdoc/files/doc/dataset_filtering_rdoc.html
I did find a recent discussion on the mailing list:
https://groups.google.com/forum/#!searchin/sequel-talk/where$20or%7Csort:date/sequel-talk/sNEUId8J9Vw/1yJteFuwAwAJ
This PR adds the documentation where I would eventually have found it. Hope this helps!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jeremyevans/sequel/1630)

Improve dataset filtering documentation when mixing AND and OR

---

lib/sequel/adapters/mysql2.rb

Mysql2 already falls back to localhost, and providing a default here actually overrides a possible hostname specified in a defaults_file.

Remove unnecessary localhost fallback

---

lib/sequel/database/logging.rb
spec/core/database_spec.rb

Allows extensions to hook into logging methods (ie. log_duration)
without having to force a logger or monkeypatch log_connection_yield.

Extract logging guard to own method

---

lib/sequel/adapters/utils/mysql_mysql2.rb

MySQL 8.0.13 returns different error numbers for foreign key constraint errors under some conditions:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-13.html#mysqld-8-0-13-errors
Sequel should recognise these as `ForeignKeyConstraintViolation` errors too.

New ForeignKeyConstraintViolation errno in MySQL 8

---

www/pages/plugins.html.erb

This adds `sequel-activerecord_connection` gem to the list of external extensions.
It also removes `sequel-jsonapi_eager` gem because we've established that it's unsafe and that `tactical_eager_loading` plugin is better anyway (I've archived that repo already).

Add sequel-activerecord_connection and remove sequel-jsonapi_eager

---

doc/code_order.rdoc

Following up on the google group discussion, simple doc PR to add a mention to the subclasses plugin where freezing is mentioned.
If you think it doesn't clutter this summary page.

Mention subclasses plugin to freeze models & finalize their associations

---

doc/dataset_filtering.rdoc

Fix spaces to use code block instead of text on dataset filtering doc.

Change code to code block in doc

---

lib/sequel/adapters/oracle.rb

Based on the causes given in the Oracle documentation I think `ORA-03135: connection lost contact` should be considered a connection error.
Causes from the oracle documentation (found [here](https://docs.oracle.com/cd/E11882_01/server.112/e17766/e2100.htm)):
1) Server unexpectedly terminated or was forced to terminate.
2) Server timed out the connection

Add ORA-03135 as a connection error

---

lib/sequel/adapters/odbc.rb

At the moment ODBC connection will try to fetch all results and store
in memory before letting the caller access to any record.
This behaviour doesn't allow for streaming, makes some operation slower, and can lead to
OOM errors if someone tries to fetch a lot of records.

Don't eager load all result sets in ODBC adapter.

---

lib/sequel/model/base.rb
spec/model/base_spec.rb

Only appears when calling methods on the class and not the dataset.
```
lib/sequel/model/base.rb:755: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
spec/model/base_spec.rb:418: warning: The called method `with_foo' is defined here
```

Fix warning for last argument as keyword param

---

.github/workflows/ci.yml

Same as https://github.com/jeremyevans/roda/pull/200 but for Sequel.
I guess truffleruby was removed unintentionally in https://github.com/jeremyevans/sequel/commit/c11fbeb56c5ab83e74f03a17c8edc5a014b237b4

Re-add truffleruby-head to CI

---

lib/sequel/extensions/pg_enum.rb

Trivial documentation fix I spotted today.

Fix typo in pg_enum documentation

---

doc/virtual_rows.rdoc

Clearly 42 - 32 + 100 = 110. In case there is any magic here that I am not aware of, it should also be documented as the result 100 is very uncertain.
For reference, here's the result from one of my machine:
```irb
>> Sequel.version
=> "5.2.0"
>> ds = DB[:features]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"features\"">
>> def self.a
|  42
|  end
=> :a
>> b=32
=> 32
>> @d=100
=> 100
>> ds.where{|o| o.c > a - b + @d}
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"features\" WHERE (\"c\" > 110)">
```

Fix document about virtual row where regular block got wrong calculation

---

doc/association_basics.rdoc

I'm not sure 100%, but looks like there is a typo in example for `:dataset` option.

Fix example for `:dataset` in associations doc

---

lib/sequel/extensions/sql_log_normalizer.rb

When using Sequel with the sequel-activerecord_connection gem, the gem's database extension [overrides `#log_connection_yield`](https://github.com/janko/sequel-activerecord_connection/blob/06e893c0343dcf1f57bfd1e07611e5975d24a787/lib/sequel/extensions/activerecord_connection.rb#L43-L47) to send SQL queries to Active Record's instrumenter, so that Sequel queries appear in the Rails logs together with Active Record queries.
This *almost* works with the new sql_log_normalizer extension, except that with sequel-activerecord_connection people typically won't have any loggers assigned to Sequel itself (since its queries are already sent to Rails logs), which causes sql_log_normalizer extension not to call the `#log_connection_yield` of descendants. Here I'm assuming the sql_log_normalizer …

Call `super` in `#log_connection_yield` in sql_log_normalizer without loggers

---

lib/sequel/adapters/shared/mysql.rb
spec/adapters/mysql_spec.rb

The value of this field is the unparsed output of whatever was returned by MySQL's DESCRIBE statement in the Extra column.

Add an :extra key for rows generated from MySQL's schema

---

lib/sequel/extensions/pg_hstore.rb

Typo introduced in https://github.com/jeremyevans/sequel/commit/60795802a37c680c76d3aff33aa118bd3994aa0e but the other case was already fixed by https://github.com/jeremyevans/sequel/commit/697f2ed77015518b75ee4c36f686e0bc155f745a

Fix typo in `pg_hstore` docs

---

www/pages/plugins.html.erb

I found it really convenient for quickly setting up Rake tasks for managing the database, similar to what Active Record provides. I was even thinking of mentioning it in the migration guide, but I didn't see official guides mentioning any 3rd-party gems, so I assumed it was a convention.

Add sequel_tools gem to list of external extensions

---

lib/sequel/dataset/actions.rb
spec/core/dataset_spec.rb

`#empty?` was not returning `false` for some non-empty datasets.
```ruby
irb(main):001:0> require "sequel"
=> true
irb(main):002:0> DB = Sequel.sqlite
=> #<Sequel::SQLite::Database: {:adapter=>:sqlite}>
irb(main):003:0> DB["select null"].empty?
=> true
irb(main):004:0> DB["values (null, 1), (2, 3)"].empty?
=> true
irb(main):005:0> DB.values([[nil, 1], [2, 3]]).empty?
=> true
irb(main):006:0> 
```

fix empty? for datasets containing null

---

spec/adapters/postgres_spec.rb
spec/adapters/sqlite_spec.rb

Just fixing typos for some of a638268ce08892cd06d7b858a2b9770f0ed2e183's new test [doc_string](https://rspec.info/documentation/3.12/rspec-core/RSpec/Core/ExampleGroup.html#it-class_method)s.
This PR does not include logic changes. In particular, it does not fix [the regression](https://github.com/jeremyevans/sequel/pull/1990#issuecomment-1416648145).

fix typo in test doc_string

---

lib/sequel/database/schema_generator.rb

I'm pretty sure there should be the underscore.
I haven't found other similar places in this file.

Fix small typo in documentation

---

lib/sequel/database/schema_methods.rb

As per https://github.com/fastruby/fast-ruby/blob/main/code/string/gsub-vs-tr.rb `tr` is faster than `gsub` for simple replacements that do not require regexp

Replace gsub with tr on_delete_clause method

---

lib/sequel/model/dataset_module.rb
spec/model/base_spec.rb

One reason you might want this is to qualify the columns in your method. For example, `where :kept, Sequel[model.table_name][:discarded_at] => nil`
See discussion https://github.com/jeremyevans/sequel/discussions/2038. I'm not sure the test is up to standards, I struggled at first so happy for any feedback/adjustments needed.

Expose the model class inside the dataset module

---

doc/sharding.rdoc

One of my senior teammates is not convinced from the documentation that `:read_only` is a special key that induces a certain automatic behavior with how read vs write queries are handled.
After I read the docs again, I was not sure anymore either. It seems implied, but never clearly stated.
This PR adds additional description that is to my best understanding. 
Please update or correct as needed. I feel that some additional clarification here could definitely help Sequel users

Sharding docs: Cleary state that :read_only is a special key

---

lib/sequel/connection_pool/threaded.rb

See <https://github.com/socketry/async/issues/99> for context/background.
This should be a temporary fix, we need to (1) establish whether there is a bug in CRuby or (2) establish whether there is faulty usage of condition variable in the connection pool. I don't know which yet.
The code related to this investigation is <https://github.com/ioquatix/ruby-condition-variable-timeout>.

Prevent connection pool starvation.

---

doc/migration.rdoc
lib/sequel/extensions/migration.rb
spec/extensions/migration_spec.rb

Reverse of "set_column_allow_null" operation is calling it with inverse of "allow_null" argument.

Make set_column_allow_null reversible

---

CHANGELOG
lib/sequel/plugins/paged_operations.rb
spec/extensions/paged_operations_spec.rb
spec/integration/plugin_test.rb
www/pages/plugins.html.erb

As proposed in https://github.com/jeremyevans/sequel/discussions/2080, now the paged_update_delete plugin supports `#paged_datasets` that can be used for other operations, we rename it to paged_operations to be more generic.

Rename paged_update_delete plugin to paged_operations

---

lib/sequel/plugins/paged_operations.rb

Update places that still refer to `paged_operations_size` to use `:rows_per_page`, and also replace `:rows_per_fetch` which is a `#paged_each` option.

Minor fixes to paged_operations plugin docs

---

Rakefile

These are unused since ce5b073d47
```
$ rake spec_w
rake aborted!
Don't know how to build task 'spec_core_w' (See the list of available tasks with `rake --tasks`)
Did you mean?  spec_core
spec_core_ext
```

Remove unused Rake tasks

---

CHANGELOG
lib/sequel/plugins/rcte_tree.rb
spec/extensions/rcte_tree_spec.rb

Support UNION style recursive common table expressions to remove duplicates by exposing a passthrough option :union_all

Update rcte plugin to allow the user to specify union_all in rcte

---

lib/sequel/plugins/list.rb
spec/extensions/list_spec.rb

Using the list plugin with the option `:top` set to something other than the default (`1`) is causing discrepancies when adding a new element to an empty list without providing a specific position value. The plugin will always set the start value to `1` and ignore the configured top option.
This PR will make the list plugin honor the configured top option when the first item in the list is added when the position value is not provided.

Honor configured `:top` option for empty lists

---

lib/sequel/plugins/validation_helpers.rb
spec/extensions/auto_validations_spec.rb
spec/extensions/validation_helpers_spec.rb

Using `empty` provides a more efficient way to check for records that violate the uniqueness constraint. Unlike `count`, which counts all matching rows, `empty` stops as soon as it finds a match, thereby reducing the load on the database. This change is particularly beneficial for tables with a large number of rows, where performance can be an issue.

Use empty? instead of count for validate uniqueness

---

lib/sequel/adapters/shared/sqlite.rb
lib/sequel/database/schema_methods.rb
spec/adapters/sqlite_spec.rb

Proposal to add support for the sqlite `WITHOUT ROWID` table option in the sqlite adapter.

sqlite adapter - allow create_table with :without_rowid option

---

lib/sequel/database/schema_methods.rb
spec/adapters/postgres_spec.rb

It's not possible to use CREATE OR REPLACE with materialized view in Postgres so we should fallback to `drop_view`/`create_view` calls when we use `create_or_replace_view` method with `:materialized` option.
Currently when `create_or_replace_view` is called you get
```
Sequel::DatabaseError: PG::SyntaxError: ERROR:  syntax error at or near "MATERIALIZED"
LINE 1: CREATE OR REPLACE MATERIALIZED VIEW "items_view" AS SELECT *...
```

Make it possible to use create_or_replace_view with materialized view.

---

lib/sequel/adapters/shared/mysql.rb

Should be supported according to https://mariadb.com/kb/en/select/#skip-locked. I have tested locally and it works well. I wasn't able to find out any specs to cover this.

Support SKIP LOCKED for MariaDB 10.6+.

---

doc/testing.rdoc

People searching for testing advice will likely look at the testing guide, so I think it would be useful to have a section on browser tests there, to make the new `temporarily_release_connection` extension more discoverable.

Update testing guide with multithreaded transactional tests

---

lib/sequel/extensions/string_agg.rb
spec/extensions/string_agg_spec.rb
spec/integration/plugin_test.rb

See https://www.sqlite.org/lang_aggfunc.html#group_concat for details
Distinct with a non-default separator is not supported due to a sqlite parser limitation

Add string_agg support on sqlite >= 3.44

---

lib/sequel/plugins/defaults_setter.rb
spec/extensions/defaults_setter_spec.rb

Add ability to set default values that depend on other values from a given record.
Example: 
If slice belongs to cake with frostings, then allow to set frostings in cake slice by default.
```
class Slice < Sequel::Model
many_to_one :cake
plugin :defaults_setter
def self.default_values
{
frosting: lambda { |slice| slice.cake&.frosting? },
}
end
end
```
```
Cake.create(frosting: true)
Slice.new(cake_id: cake.id).frosting # => true
```

 Allow proc default values that depend on other values

---

lib/sequel/extensions/pg_auto_parameterize.rb
spec/extensions/pg_auto_parameterize_spec.rb

Before this change, if you enabled the pg_auto_parameterize extension, all inserts were limited to 40 rows at a time.
Now, you can use the `#no_auto_parameterize` method to turn off this behavior since inserts without parameterization can handle much higher rows at a time.

Support using no_auto_parameterize to remove the insert limit

---

lib/sequel/model/base.rb

I just learned of the `Model.first` alternative `Model[]`, but when reading the docs I initially attempted to use it as the docs show `Model.[]` which is a syntax error. My apologies if this is intentional, but it was confusing for me as a Sequel noob and thought I'd help clarify for others.

Update model docs for clarity

---

www/pages/plugins.html.erb

Hi Jeremy, 
Thanks for all your hard work on Sequel!
I wrote a small [plugin](https://github.com/eriklovmo/sequel_more_than) to decide whether a dataset's row count is less than, less than or equal to, greater than, or greater than or equal to a given number. This pull request adds it to the Sequel website's list of external extensions.

Add the more_than plugin to list of exernal extensions

---

doc/sharding.rdoc

This PR fixing a bit of confusing statement, because there are only 2 queries.

Fix confusing 'also' in server_block doc

---

lib/sequel/extensions/pg_enum.rb
spec/extensions/pg_enum_spec.rb

By not providing the scalar OID, the `pg_array` plugin will lookup each custom type individually. I've updated the `pg_enum` plugin to call `pg_array`'s `#register_array_type` with the scalar type's OID so it doesn't have to do the lookup. We've been running this in production today and we're no longer seeing our app make these a query per custom type.
Existing discussion: https://github.com/jeremyevans/sequel/discussions/2278

Reduce queries made on startup when the `pg_enum` and `pg_array` plugins are enabled

---

CHANGELOG
lib/sequel/plugins/forbid_lazy_load.rb
spec/extensions/forbid_lazy_load_spec.rb

This one was conceived and discussed more thoroughly over in #2286. The
basic idea is that the `forbid_lazy_load` plugin disables lazy loading
on specific model instances, but also broadly on any models loaded
through an association. The latter can be detrimental when trying to cut
over to eager loading incrementally and where it's hard to get an entire
codebase converted all at once.
Here, the `forbid_lazy_load` plugin picks up a new `allow_by_default`
option. When it's set to true, lazy loading can still be forbidden
normally on an instance-by-instance basis, but it's not forbidden
through associations. This should make incremental migrations to eager
loading with `forbid_lazy_load` somewhat easier to do.

Add `allow_by_default` option for `forbid_lazy_load` plugin
